// <auto-generated />
using System;
using DCI.Entities.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DCI.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220508213927_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DCI.Core.ViolenceType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ChildAbuse")
                        .HasColumnType("bit");

                    b.Property<bool>("CyberBullying")
                        .HasColumnType("bit");

                    b.Property<bool>("Defilement")
                        .HasColumnType("bit");

                    b.Property<bool>("DenialOfResources")
                        .HasColumnType("bit");

                    b.Property<bool>("EarlyMarriage")
                        .HasColumnType("bit");

                    b.Property<bool>("FemaleGenitalMutilation")
                        .HasColumnType("bit");

                    b.Property<bool>("ForcedMarriage")
                        .HasColumnType("bit");

                    b.Property<bool>("PhysicalAssault")
                        .HasColumnType("bit");

                    b.Property<bool>("Psychological")
                        .HasColumnType("bit");

                    b.Property<bool>("Rape")
                        .HasColumnType("bit");

                    b.Property<bool>("SocialAssault")
                        .HasColumnType("bit");

                    b.Property<bool>("ViolationOfProperty")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ViolenceType");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000000",
                            ChildAbuse = true,
                            CyberBullying = true,
                            Defilement = true,
                            DenialOfResources = true,
                            EarlyMarriage = true,
                            FemaleGenitalMutilation = true,
                            ForcedMarriage = true,
                            PhysicalAssault = true,
                            Psychological = true,
                            Rape = true,
                            SocialAssault = true,
                            ViolationOfProperty = true
                        });
                });

            modelBuilder.Entity("DCI.Entities.Entities.Approval", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Approval");

                    b.HasData(
                        new
                        {
                            Id = "5e319b4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 461, DateTimeKind.Utc).AddTicks(6581),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-08d9b6be7c9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(510),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-08d9b6be7d9a",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(768),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e21db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(819),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "4e31db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(861),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6a79-487e-4c9e-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(926),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9a-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(967),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-5c9e-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(1006),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-18d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(1143),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-437e-4c9e-08d9b6be7d9e",
                            ActionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(1199),
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DCI.Entities.Entities.Case", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalActionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("CSOUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFatal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerpetratorArrested")
                        .HasColumnType("bit");

                    b.Property<string>("LGA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateOfCase")
                        .HasColumnType("int");

                    b.Property<string>("Statement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViolenceTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalActionId");

                    b.HasIndex("CSOUserId");

                    b.HasIndex("ViolenceTypeId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = "5e319b4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ApprovalActionId = "5e319b4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 502, DateTimeKind.Utc).AddTicks(6397),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "First Case",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-08d9b6be7c9e",
                            ApprovalActionId = "5e31db4e-6e79-487e-4c9e-08d9b6be7c9e",
                            ApprovalStatus = 4,
                            CSOUserId = "eeae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(641),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Abeokuta",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Ogun",
                            StateOfCase = 1,
                            Statement = "statement",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-08d9b6be7d9a",
                            ApprovalActionId = "5e31db4e-6e79-487e-4c9e-08d9b6be7d9a",
                            ApprovalStatus = 4,
                            CSOUserId = "eeae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(828),
                            IsDeleted = false,
                            IsFatal = false,
                            IsPerpetratorArrested = false,
                            LGA = "Ogun",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Ogun",
                            StateOfCase = 0,
                            Statement = "Second Statement",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e21db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ApprovalActionId = "5e21db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(897),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = true,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 0,
                            Statement = "Second case",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "4e31db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ApprovalActionId = "4e31db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(1008),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "Third case",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6a79-487e-4c9e-08d9b6be7d9e",
                            ApprovalActionId = "5e31db4e-6a79-487e-4c9e-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(1072),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "fourth",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9a-08d9b6be7d9e",
                            ApprovalActionId = "5e31db4e-6e79-487e-4c9a-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(1119),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "fifth",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-5c9e-08d9b6be7d9e",
                            ApprovalActionId = "5e31db4e-6e79-487e-5c9e-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(1167),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "sixth",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-18d9b6be7d9e",
                            ApprovalActionId = "5e31db4e-6e79-487e-4c9e-18d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(1214),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "seventh",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-437e-4c9e-08d9b6be7d9e",
                            ApprovalActionId = "5e31db4e-6e79-437e-4c9e-08d9b6be7d9e",
                            ApprovalStatus = 4,
                            CSOUserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 503, DateTimeKind.Utc).AddTicks(1263),
                            IsDeleted = false,
                            IsFatal = true,
                            IsPerpetratorArrested = false,
                            LGA = "Lagos",
                            LastDateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Lagos",
                            StateOfCase = 1,
                            Statement = "eight",
                            ViolenceTypeId = "00000000-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("DCI.Entities.Entities.DCIUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCSO")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b8633e2d-a33b-45e6-8329-1958b3252bbd",
                            AccessFailedCount = 0,
                            Activated = false,
                            ConcurrencyStamp = "dca8dc13-c492-458d-a17f-dfb62840e6de",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 463, DateTimeKind.Utc).AddTicks(9380),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@dci.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            Gender = 0,
                            IsAdmin = true,
                            IsCSO = false,
                            IsDeleted = false,
                            IsSupervisor = false,
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "Admin@dci.com",
                            NormalizedUserName = "Admin@dci.com",
                            PasswordHash = "AQAAAAEAACcQAAAAED3D5dUaE+Z6DZXcTWbz19Irgh4ipNDw4gwby7WMXbwlNi4wcPezSHAPeK5/W3h0Fg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bcc30d81-b82f-4369-8dd7-bc95cc4d1e1b",
                            State = "Lagos",
                            TwoFactorEnabled = false,
                            UserName = "Admin@dci.com",
                            UserType = 2
                        },
                        new
                        {
                            Id = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            AccessFailedCount = 0,
                            Activated = false,
                            ConcurrencyStamp = "9fcb3b00-9484-4c84-b06f-cdd6e51e3c9d",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 475, DateTimeKind.Utc).AddTicks(552),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "CSO@dci.com",
                            EmailConfirmed = true,
                            FirstName = "CSO",
                            Gender = 0,
                            IsAdmin = false,
                            IsCSO = true,
                            IsDeleted = false,
                            IsSupervisor = false,
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "CSO",
                            LockoutEnabled = false,
                            NormalizedEmail = "CSO@dci.com",
                            NormalizedUserName = "CSO@dci.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ2wjnXSkmMbP18aIP7A7DhXSBQvz03CW60y4NBxUPKITXemGYdx1+fGL8PREqO6VA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97093800-6bb2-46e6-949a-57864d2ebfe8",
                            State = "Lagos",
                            TwoFactorEnabled = false,
                            UserName = "CSO@dci.com",
                            UserType = 0
                        },
                        new
                        {
                            Id = "eeae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            AccessFailedCount = 0,
                            Activated = false,
                            ConcurrencyStamp = "249641f9-6667-40eb-92f1-832dd6d2c26a",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 484, DateTimeKind.Utc).AddTicks(2481),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "CSOSecond@dci.com",
                            EmailConfirmed = true,
                            FirstName = "Second",
                            Gender = 0,
                            IsAdmin = false,
                            IsCSO = true,
                            IsDeleted = false,
                            IsSupervisor = false,
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Second",
                            LockoutEnabled = false,
                            NormalizedEmail = "CSOSecond@dci.com",
                            NormalizedUserName = "CSOSecond@dci.com",
                            PasswordHash = "AQAAAAEAACcQAAAAECMiUdiD+yIUMUMbT69HtLCHysTerEgYFT1mUFUlt4zASmaH3U6h1sOnn/7U2clmuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f70d266d-5814-418a-8e45-96edbb110be5",
                            State = "Ogun",
                            TwoFactorEnabled = false,
                            UserName = "CSOSecond@dci.com",
                            UserType = 0
                        },
                        new
                        {
                            Id = "5e31db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            AccessFailedCount = 0,
                            Activated = false,
                            ConcurrencyStamp = "79767d03-2323-4983-8f42-d319b7c5f6de",
                            CreatedOnUtc = new DateTime(2022, 5, 8, 21, 39, 26, 492, DateTimeKind.Utc).AddTicks(5634),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Supervisor@dci.com",
                            EmailConfirmed = true,
                            FirstName = "Supervisor",
                            Gender = 0,
                            IsAdmin = false,
                            IsCSO = false,
                            IsDeleted = false,
                            IsSupervisor = true,
                            LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Supervisor",
                            LockoutEnabled = false,
                            NormalizedEmail = "Supervisor@dci.com",
                            NormalizedUserName = "Supervisor@dci.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEBPd2Fikc3U13m4Y+LJwxwNmbNZGY6937d2zN004ZXupWQIjn7uBTyNH/jy2D4CzqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf20fc5e-d5d3-4f4d-81af-efd3395ec049",
                            State = "Lagos",
                            TwoFactorEnabled = false,
                            UserName = "Supervisor@dci.com",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "54a281f5-230c-407d-acbc-442796a58e89",
                            Name = "ADMIN",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "fe8d7501-6cb1-4d99-4c9f-08d9b6be7d9e",
                            ConcurrencyStamp = "be07866f-c63a-46d8-9dbb-354048279aa1",
                            Name = "SUPERVISOR",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = "e82fe09a-2419-4b9b-8a2c-b5001e71c997",
                            ConcurrencyStamp = "23818d71-cc79-4910-86c7-3ffbe96f95af",
                            Name = "CSO",
                            NormalizedName = "CSO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "b8633e2d-a33b-45e6-8329-1958b3252bbd",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "5e31db4e-6e79-487e-4c9e-08d9b6be7d9e",
                            RoleId = "fe8d7501-6cb1-4d99-4c9f-08d9b6be7d9e"
                        },
                        new
                        {
                            UserId = "cdae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            RoleId = "e82fe09a-2419-4b9b-8a2c-b5001e71c997"
                        },
                        new
                        {
                            UserId = "eeae8cc2-adec-4ab1-4ca0-08d9b6be7d9e",
                            RoleId = "e82fe09a-2419-4b9b-8a2c-b5001e71c997"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DCI.Entities.Entities.Case", b =>
                {
                    b.HasOne("DCI.Entities.Entities.Approval", "ApprovalAction")
                        .WithMany()
                        .HasForeignKey("ApprovalActionId");

                    b.HasOne("DCI.Entities.Entities.DCIUser", "CSOUser")
                        .WithMany()
                        .HasForeignKey("CSOUserId");

                    b.HasOne("DCI.Core.ViolenceType", "ViolenceType")
                        .WithMany()
                        .HasForeignKey("ViolenceTypeId");
                });

            modelBuilder.Entity("DCI.Entities.Entities.DCIUser", b =>
                {
                    b.OwnsMany("DCI.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("DCIUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DCIUserId", "Id");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("DCIUserId");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DCI.Entities.Entities.DCIUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DCI.Entities.Entities.DCIUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCI.Entities.Entities.DCIUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DCI.Entities.Entities.DCIUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
